# Generated by Django 5.2.8 on 2025-11-18 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0002_alter_profile_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
