# Generated by Django 5.2.8 on 2025-11-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0003_alter_profile_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
